// components/table/demos/loading/index.vue
<template>
    <div>
        <Table 
            :data="[
                {a: '第一行', b: '哈哈2'}, 
                {a: '第二行', b: '哈哈2'},
                {a: '第三行', b: '哈哈3'},
            ]"
            :loading="!!loading"
        >
            <TableColumn key="a" title="表头1" />
            <TableColumn key="b" title="表头2" />
        </Table>
        切换loading状态: <KSwitch v-model="loading"></KSwitch>
    </div>
</template>
<script>
import {Table, TableColumn} from 'kpc/components/table';
import {Switch as KSwitch} from 'kpc/components/switch';

export default {
    components: {
        Table, TableColumn, KSwitch
    },
    data() {
        return {
            "loading": null
        }
    },
}
</script>

// components/table/demos/loading/index.jsx
import React from 'react';
import {Table, TableColumn} from 'kpc/components/table';
import {Switch} from 'kpc/components/switch';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }

    render() {
        return (
            <div>
                <Table 
                    data={[
                        {a: '第一行', b: '哈哈2'}, 
                        {a: '第二行', b: '哈哈2'},
                        {a: '第三行', b: '哈哈3'},
                    ]}
                    loading={!!this.state.loading}
                >
                    <TableColumn key="a" title="表头1" />
                    <TableColumn key="b" title="表头2" />
                </Table>
                切换loading状态: <Switch value={this.state.loading} on$change-value={(c, loading) => this.setState({loading})}></Switch>
            </div>
        )
    }
}
