// components/spin/demos/overlay/index.vue
<template>
    <div class="wrapper">
        <Table :data="data">
            <TableColumn key="a" title="表头1" />
            <TableColumn key="b" title="表头2" />
        </Table>
        <Spin overlay />
    </div>
</template>
<script>
import Spin from 'kpc/components/spin';
import {Table, TableColumn} from 'kpc/components/table';

export default {
    components: {
        Spin, Table, TableColumn
    },
    data() {
        return {
            "data": [
                {
                    "a": "第一行",
                    "b": "哈哈2"
                },
                {
                    "a": "第二行",
                    "b": "哈哈2"
                },
                {
                    "a": "第三行",
                    "b": "哈哈3"
                }
            ]
        }
    },
}
</script>

// components/spin/demos/overlay/index.jsx
import React from 'react';
import Spin from 'kpc/components/spin';
import {Table, TableColumn} from 'kpc/components/table';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            "data": [
                {
                    "a": "第一行",
                    "b": "哈哈2"
                },
                {
                    "a": "第二行",
                    "b": "哈哈2"
                },
                {
                    "a": "第三行",
                    "b": "哈哈3"
                }
            ]
        };
    }

    render() {
        return (
            <div className="wrapper">
                <Table data={this.state.data}>
                    <TableColumn key="a" title="表头1" />
                    <TableColumn key="b" title="表头2" />
                </Table>
                <Spin overlay />
            </div>
        )
    }
}
