// components/timeline/demos/custom/index.jsx
import React from 'react';
import {Timeline, TimelineItem} from 'kpc/components/timeline';

export default class extends React.Component {
    render() {
        return (
            <Timeline>
                <TimelineItem type="success"
                    b-dot={<><i className="ion-trophy"></i></>}
                >
                    August
                </TimelineItem>
                <TimelineItem>July</TimelineItem>
                <TimelineItem>June</TimelineItem>
                <TimelineItem>May</TimelineItem>
            </Timeline>
        )
    }
}

// components/timeline/demos/custom/index.vue
<template>
    <Timeline>
        <TimelineItem type="success">
            <template slot="dot"><i class="ion-trophy"></i></template>
            August
        </TimelineItem>
        <TimelineItem>July</TimelineItem>
        <TimelineItem>June</TimelineItem>
        <TimelineItem>May</TimelineItem>
    </Timeline>
</template>
<script>
import {Timeline, TimelineItem} from 'kpc-vue/components/timeline';

export default {
    components: {
        Timeline, TimelineItem
    },
}
</script>
