// components/datepicker/demos/datetime/index.jsx
import React from 'react';
import Datepicker from 'kpc/components/datepicker';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }

    render() {
        return (
            <div>
                <Datepicker type="datetime" value={this.state.datetime1} on$change-value={(c, datetime1) => this.setState({datetime1})} />
                <Datepicker type="datetime" value={this.state.datetime2}
                    on$change-value={(c, datetime2) => this.setState({datetime2})} 
                    placeholder="时间精确到小时"
                    disabledMinutes
                    disabledSeconds
                />
            </div>
        )
    }
}

// components/datepicker/demos/datetime/index.vue
<template>
    <div>
        <Datepicker type="datetime" v-model="datetime1" />
        <Datepicker type="datetime" v-model="datetime2" 
            placeholder="时间精确到小时"
            disabledMinutes
            disabledSeconds
        />
    </div>
</template>
<script>
import Datepicker from 'kpc/components/datepicker';

export default {
    components: {
        Datepicker
    },
    data() {
        return {
            "datetime1": null,
            "datetime2": null
        }
    },
}
</script>
