// components/upload/demos/directory/index.jsx
import React from 'react';
import Upload from 'kpc-react/components/upload';
import Button from 'kpc-react/components/button';
import './index.styl';

export default class Demo extends React.Component {
    render() {
        return (
            <Upload 
                directory
                action="//jsonplaceholder.typicode.com/posts/"
            />
        )
    }
}

// components/upload/demos/directory/index.vue
<template>
    <Upload 
        directory
        action="//jsonplaceholder.typicode.com/posts/"
    />
</template>
<script>
import Upload from 'kpc-vue/components/upload';
import Button from 'kpc-vue/components/button';

export default {
    components: {
        Upload, Button
    },
}
</script>
<style lang="stylus" src="./index.styl"></style>
