// components/input/demos/size/index.jsx
import React from 'react';
import Input from 'kpc/components/input';
import Button from 'kpc/components/button';

export default class extends React.Component {
    render() {
        return (
            <div>
                <Input size="large" value="large" />
                <br />
                <Input value="default" />
                <br />
                <Input value="small" size="small" />
                <Input size="small" placeholder="please enter"
                    b-prepend={<>http://</>}
                    b-append={<>.com</>}
                >
                </Input>
                <Input size="small" placeholder="please enter"
                    b-prefix={<><i className="ion-earth"></i></>}
                    b-suffix={<><i className="ion-ios-search"></i></>}
                    b-append={<><Button size="small" icon type="primary"><i className="ion-ios-search"></i></Button></>}
                >
                </Input>
                <Input size="small" placeholder="please enter" clearable
                    b-append={<><Button type="primary" size="small">Search</Button></>}
                >
                </Input>
            
                <Input value="mini" size="mini" />
            </div>
        )
    }
}

// components/input/demos/size/index.vue
<template>
    <div>
        <Input size="large" value="large" />
        <br />
        <Input value="default" />
        <br />
        <Input value="small" size="small" />
        <Input size="small" placeholder="please enter">
            <template slot="prepend">http://</template>
            <template slot="append">.com</template>
        </Input>
        <Input size="small" placeholder="please enter">
            <template slot="prefix"><i class="ion-earth"></i></template>
            <template slot="suffix"><i class="ion-ios-search"></i></template>
            <template slot="append"><Button size="small" icon type="primary"><i class="ion-ios-search"></i></Button></template>
        </Input>
        <Input size="small" placeholder="please enter" clearable>
            <template slot="append"><Button type="primary" size="small">Search</Button></template>
        </Input>
    
        <Input value="mini" size="mini" />
    </div>
</template>
<script>
import Input from 'kpc/components/input';
import Button from 'kpc/components/button';

export default {
    components: {
        Input, Button
    },
}
</script>
