// components/input/demos/clearable/index.jsx
import React from 'react';
import Input from 'kpc/components/input';

export default class extends React.Component {
    render() {
        return (
            <div>
                <Input clearable placeholder="please enter" />
                <br />
                <Input clearable placeholder="please enter"
                    b-suffix={<><i className="ion-ios-search"></i></>}
                >
                </Input>
            </div>
        )
    }
}

// components/input/demos/clearable/index.vue
<template>
    <div>
        <Input clearable placeholder="please enter" />
        <br />
        <Input clearable placeholder="please enter">
            <template slot="suffix"><i class="ion-ios-search"></i></template>
        </Input>
    </div>
</template>
<script>
import Input from 'kpc/components/input';

export default {
    components: {
        Input
    },
}
</script>
