// components/input/demos/search/index.vue
<template>
    <div>
        <Search @submit="_search" />
        <br />
        <Search type="line" @submit="_search" />
    </div>
</template>
<script>
import {Search} from 'kpc/components/input';

import Message from 'kpc/components/message';

export default {
    components: {
        Search
    },
    methods: {
        _search(keywords) {
            Message.success('Search by keywords: ' + keywords);
        },
    },
}
</script>

// components/input/demos/search/index.jsx
import React from 'react';
import {Search} from 'kpc/components/input';


export default class extends React.Component {
    constructor(props) {
        super(props);
        this._search = this._search.bind(this);
    }

    _search(keywords) {
        Message.success('Search by keywords: ' + keywords);
    }
    
    render() {
        return (
            <div>
                <Search onSubmit={this._search} />
                <br />
                <Search type="line" onSubmit={this._search} />
            </div>
        )
    }
}
