// components/colorpicker/demos/presets/index.vue
<template>
    <div>
        <Colorpicker v-model="color1"
            :presets="['transparent', 'red', '#d99123', 'rgb(255, 51, 33)', 'hsl(126, 54%, 46%)']"
        />
        <Colorpicker v-model="color2"
            :presets="[]"
        />
    </div>
</template>
<script>
import Colorpicker from 'kpc-vue/components/colorpicker';

export default {
    components: {
        Colorpicker
    },
    data() {
        return {
            "color1": "#36acef",
            "color2": "#d99123"
        }
    },
}
</script>
<style lang="stylus" src="./index.styl"></style>

// components/colorpicker/demos/presets/index.jsx
import React from 'react';
import Colorpicker from 'kpc-react/components/colorpicker';
import './index.styl';

export default class Demo extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            "color1": "#36acef",
            "color2": "#d99123"
        };
    }

    render() {
        return (
            <div>
                <Colorpicker value={this.state.color1}
                    on$change-value={(c, color1) => this.setState({color1})}
                    presets={['transparent', 'red', '#d99123', 'rgb(255, 51, 33)', 'hsl(126, 54%, 46%)']}
                />
                <Colorpicker value={this.state.color2}
                    on$change-value={(c, color2) => this.setState({color2})}
                    presets={[]}
                />
            </div>
        )
    }
}
