// components/code/demos/theme/index.vue
<template>
    <div>
        主题：<ButtonGroup v-model="theme" checkType="radio">
            <Button v-for="(value, key) in ['vs', 'vs-dark', 'hc-black']"
                :value="value"
            >{{ value }}</Button>
        </ButtonGroup>
        <Code v-model="value" height="200px" :theme="theme" />
    </div>
</template>
<script>
import Code from 'kpc-vue/components/code';
import {ButtonGroup, Button} from 'kpc-vue/components/button';

const code = `function test() {
    console.log('hello world');
}`;
export default {
    components: {
        Code, ButtonGroup, Button
    },
    data() {
        return {
            "theme": null,
            "value": null
        }
    },
}
</script>
<style lang="stylus" src="./index.styl"></style>

// components/code/demos/theme/index.jsx
import React from 'react';
import Code from 'kpc-react/components/code';
import {ButtonGroup, Button} from 'kpc-react/components/button';
import './index.styl';
const code = `function test() {
    console.log('hello world');
}`;

export default class Demo extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }

    render() {
        return (
            <div>
                主题：<ButtonGroup value={this.state.theme} on$change-value={(c, theme) => this.setState({theme})} checkType="radio">
                    {['vs', 'vs-dark', 'hc-black'].map((value, key) => {
                        return (
                            <Button
                                value={value}
                            >{value}</Button>
                        )
                    })}
                </ButtonGroup>
                <Code value={this.state.value} on$change-value={(c, value) => this.setState({value})} height="200px" theme={this.state.theme} />
            </div>
        )
    }
}
