// components/tip/demos/closable/index.vue
<template>
    <div>
        <Tip v-for="(value, key) in ['default', 'primary', 'success', 'warning', 'danger']"
            :key="value"
            :type="value"
            closable
        >{{ value }}</Tip>
        <Tip closable>
            custom closing content
            <template slot="close">No longer show</template>
        </Tip>
    </div>
</template>
<script>
import Tip from 'kpc/components/tip';

export default {
    components: {
        Tip
    },
}
</script>

// components/tip/demos/closable/index.jsx
import React from 'react';
import Tip from 'kpc/components/tip';

export default class extends React.Component {
    render() {
        return (
            <div>
                {['default', 'primary', 'success', 'warning', 'danger'].map((value, key) => {
                    return (
                        <Tip
                            key={value}
                            type={value}
                            closable
                        >{value}</Tip>
                    )
                })}
                <Tip closable
                    b-close={<>No longer show</>}
                >
                    custom closing content
                </Tip>
            </div>
        )
    }
}
