// components/scrollSelect/demos/disable/index.vue
<template>
    <ScrollSelect
        :data="generateData"
        v-model="value"
        :disable="disable"
    />
</template>
<script>
import ScrollSelect from 'kpc/components/scrollSelect';

export default {
    components: {
        ScrollSelect
    },
    data() {
        return {
            "value": 2018
        }
    },
    methods: {
        generateData(value) {
            const start = value - 5;
            return Array.apply(null, {length: 10})
                .map((v, i) => {
                    const year = start + i; 
                    return {
                        label: `${year}年`,
                        value: year
                    };
                });
        },
        disable(value) {
            // 排除闰年
            return value % 4 === 0 && (value % 100 !== 0 || value % 400 === 0);
        },
    },
}
</script>

// components/scrollSelect/demos/disable/index.jsx
import React from 'react';
import ScrollSelect from 'kpc/components/scrollSelect';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            "value": 2018
        };
        this.generateData = this.generateData.bind(this);
        this.disable = this.disable.bind(this);
    }

    generateData(value) {
        const start = value - 5;
        return Array.apply(null, {length: 10})
            .map((v, i) => {
                const year = start + i; 
                return {
                    label: `${year}年`,
                    value: year
                };
            });
    }
    
    disable(value) {
        // 排除闰年
        return value % 4 === 0 && (value % 100 !== 0 || value % 400 === 0);
    }
    
    render() {
        return (
            <ScrollSelect
                data={this.generateData}
                value={this.state.value}
                on$change-value={(c, value) => this.setState({value})}
                disable={this.disable}
            />
        )
    }
}
