// components/select/demos/group/index.jsx
import React from 'react';
import {Select, Option, OptionGroup} from 'kpc/components/select';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }

    render() {
        return (
            <div>
                <Select value={this.state.day} on$change-value={(c, day) => this.setState({day})}>
                    <OptionGroup label="工作日">
                        <Option value="Monday">星期一</Option>
                        <Option value="Tuesday">星期二</Option>
                        <Option value="Wednesday">星期三</Option>
                        <Option value="Thursday">星期四</Option>
                        <Option value="Friday">星期五</Option>
                    </OptionGroup>
                    <OptionGroup label="休息日">
                        <Option value="Saturday">星期六</Option>
                        <Option value="Sunday">星期天</Option>
                    </OptionGroup>
                </Select>
                <Select value={this.state.day} on$change-value={(c, day) => this.setState({day})} card>
                    <OptionGroup label="工作日">
                        <Option value="Monday">星期一</Option>
                        <Option value="Tuesday">星期二</Option>
                        <Option value="Wednesday">星期三</Option>
                        <Option value="Thursday">星期四</Option>
                        <Option value="Friday">星期五</Option>
                    </OptionGroup>
                    <OptionGroup
                        b-label={<><i className="ion-wineglass"></i>休息日</>}
                    >
                        <Option value="Saturday">星期六</Option>
                        <Option value="Sunday">星期天</Option>
                    </OptionGroup>
                </Select>
            </div>
        )
    }
}

// components/select/demos/group/index.vue
<template>
    <div>
        <Select v-model="day">
            <OptionGroup label="工作日">
                <Option value="Monday">星期一</Option>
                <Option value="Tuesday">星期二</Option>
                <Option value="Wednesday">星期三</Option>
                <Option value="Thursday">星期四</Option>
                <Option value="Friday">星期五</Option>
            </OptionGroup>
            <OptionGroup label="休息日">
                <Option value="Saturday">星期六</Option>
                <Option value="Sunday">星期天</Option>
            </OptionGroup>
        </Select>
        <Select v-model="day" card>
            <OptionGroup label="工作日">
                <Option value="Monday">星期一</Option>
                <Option value="Tuesday">星期二</Option>
                <Option value="Wednesday">星期三</Option>
                <Option value="Thursday">星期四</Option>
                <Option value="Friday">星期五</Option>
            </OptionGroup>
            <OptionGroup>
                <template slot="label"><i class="ion-wineglass"></i>休息日</template>
                <Option value="Saturday">星期六</Option>
                <Option value="Sunday">星期天</Option>
            </OptionGroup>
        </Select>
    </div>
</template>
<script>
import {Select, Option, OptionGroup} from 'kpc/components/select';

export default {
    components: {
        Select, Option, OptionGroup
    },
    data() {
        return {
            "day": null
        }
    },
}
</script>
