// components/tree/demos/uncorrelated/index.jsx
import React from 'react';
import Tree from 'kpc/components/tree';
import './index.styl';

export default class Demo extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            "data": [
                {
                    "label": "First floor-1",
                    "children": [
                        {
                            "label": "Second floor-1.1",
                            "children": [
                                {
                                    "label": "Third floor-1.1.1"
                                }
                            ]
                        }
                    ]
                },
                {
                    "label": "First floor-2",
                    "children": [
                        {
                            "label": "Second floor-2.1",
                            "children": [
                                {
                                    "label": "Third floor-2.1.1",
                                    "key": "floor-2.1.1"
                                },
                                {
                                    "label": "Third floor-2.1.2"
                                }
                            ]
                        },
                        {
                            "label": "Second floor-2.2",
                            "disabled": true,
                            "children": [
                                {
                                    "label": "Third floor-2.2.1"
                                }
                            ]
                        }
                    ]
                }
            ],
            "checkedKeys": [
                "floor-2.1.1"
            ]
        };
    }

    render() {
        const data = this.state.data;
    
        return (
            <Tree data={data} 
                checkbox
                checkedKeys={this.state.checkedKeys}
                on$change-checkedKeys={(c, checkedKeys) => this.setState({checkedKeys})}
                uncorrelated
            />
        )
    }
}

// components/tree/demos/uncorrelated/index.vue
<template>
    <Tree :data="data" 
        checkbox
        :checkedKeys.sync="checkedKeys"
        uncorrelated
    />
</template>
<script>
import Tree from 'kpc-vue/components/tree';

export default {
    components: {
        Tree
    },
    data() {
        return {
            "checkedKeys": [
                "floor-2.1.1"
            ],
            "data": [
                {
                    "label": "First floor-1",
                    "children": [
                        {
                            "label": "Second floor-1.1",
                            "children": [
                                {
                                    "label": "Third floor-1.1.1"
                                }
                            ]
                        }
                    ]
                },
                {
                    "label": "First floor-2",
                    "children": [
                        {
                            "label": "Second floor-2.1",
                            "children": [
                                {
                                    "label": "Third floor-2.1.1",
                                    "key": "floor-2.1.1"
                                },
                                {
                                    "label": "Third floor-2.1.2"
                                }
                            ]
                        },
                        {
                            "label": "Second floor-2.2",
                            "disabled": true,
                            "children": [
                                {
                                    "label": "Third floor-2.2.1"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    },
}
</script>
<style lang="stylus" src="./index.styl"></style>
