// components/input/demos/textarea/index.jsx
import React from 'react';
import Input from 'kpc/components/input';

export default class extends React.Component {
    render() {
        return (
            <div>
                <Input type="textarea" placeholder="please enter" />
                <br />
                <Input type="textarea" rows="5" placeholder="please enter" />
            </div>
        )
    }
}

// components/input/demos/textarea/index.vue
<template>
    <div>
        <Input type="textarea" placeholder="please enter" />
        <br />
        <Input type="textarea" rows="5" placeholder="please enter" />
    </div>
</template>
<script>
import Input from 'kpc-vue/components/input';

export default {
    components: {
        Input
    },
}
</script>
