// components/steps/demos/error/index.jsx
import React from 'react';
import {Steps, Step} from 'kpc/components/steps';

export default class extends React.Component {
    render() {
        return (
            <Steps value="1" status="error">
                <Step title="选择配置">请选择主机的配置信息</Step>
                <Step title="选择弹性IP">请选择主机弹性IP的配置信息</Step>
                <Step title="设置VPC" />
            </Steps>
        )
    }
}

// components/steps/demos/error/index.vue
<template>
    <Steps value="1" status="error">
        <Step title="选择配置">请选择主机的配置信息</Step>
        <Step title="选择弹性IP">请选择主机弹性IP的配置信息</Step>
        <Step title="设置VPC" />
    </Steps>
</template>
<script>
import {Steps, Step} from 'kpc-vue/components/steps';

export default {
    components: {
        Steps, Step
    },
}
</script>
