// components/slider/demos/range/index.vue
<template>
    <Slider isRange v-model="values" />
</template>
<script>
import Slider from 'kpc/components/slider';

export default {
    components: {
        Slider
    },
    data() {
        return {
            "values": [
                50,
                76
            ]
        }
    },
}
</script>

// components/slider/demos/range/index.jsx
import React from 'react';
import Slider from 'kpc/components/slider';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            "values": [
                50,
                76
            ]
        };
    }

    render() {
        return (
            <Slider isRange value={this.state.values} on$change-value={(c, values) => this.setState({values})} />
        )
    }
}
