// components/colorpicker/demos/size/index.jsx
import React from 'react';
import Colorpicker from 'kpc-react/components/colorpicker';
import './index.styl';

export default class Demo extends React.Component {
    render() {
        return (
            <div>
                {['large', 'default', 'small', 'mini'].map((value, key) => {
                    return (
                        <Colorpicker
                            size={value}
                            value="#36acef"
                        />
                    )
                })}
            </div>
        )
    }
}

// components/colorpicker/demos/size/index.vue
<template>
    <div>
        <Colorpicker v-for="(value, key) in ['large', 'default', 'small', 'mini']"
            :size="value"
            value="#36acef"
        />
    </div>
</template>
<script>
import Colorpicker from 'kpc-vue/components/colorpicker';

export default {
    components: {
        Colorpicker
    },
}
</script>
<style lang="stylus" src="./index.styl"></style>
