// components/switch/demos/onOff/index.jsx
import React from 'react';
import {Switch} from 'kpc/components/switch';

export default class extends React.Component {
    render() {
        return (
            <div>
                <Switch on="开" off="关" />
                <Switch value={true}
                    b-on={<><i className="ion-ios-checkmark-empty"></i></>}
                    b-off={<><i className="ion-ios-close-empty"></i></>}
                >
                </Switch>
            </div>
        )
    }
}

// components/switch/demos/onOff/index.vue
<template>
    <div>
        <KSwitch on="开" off="关" />
        <KSwitch :value="true">
            <template slot="on"><i class="ion-ios-checkmark-empty"></i></template>
            <template slot="off"><i class="ion-ios-close-empty"></i></template>
        </KSwitch>
    </div>
</template>
<script>
import {Switch as KSwitch} from 'kpc/components/switch';

export default {
    components: {
        KSwitch
    },
}
</script>
