// components/tabs/demos/data/index.jsx
import React from 'react';
import {Tabs, Tab} from 'components/tabs';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            "tab": "ruleout"
        };
    }

    render() {
        return (
            <div>
                <Tabs 
                    data={[
                        {
                            text: '入站规则',
                            value: 'rulein',
                        },
                        {
                            text: '出站规则',
                            value: 'ruleout',
                        },
                        {
                            text: '关联云主机',
                            value: 'relatedVM',
                        }
                    ]} 
                    value={this.state.tab}
                    on$change-value={(c, tab) => this.setState({tab})}  
                />
            
                <div className="content">
                    {this.state.tab == 'rulein' ?
                        <div>入站规则</div> :
                        this.state.tab == 'ruleout' ?
                            <div>出站规则</div> :
                            <div>关联云主机</div> 
                    }
                </div>
            </div>
        )
    }
}

// components/tabs/demos/data/index.vue
<template>
    <div>
        <Tabs 
            :data="[
                {
                    text: '入站规则',
                    value: 'rulein',
                },
                {
                    text: '出站规则',
                    value: 'ruleout',
                },
                {
                    text: '关联云主机',
                    value: 'relatedVM',
                }
            ]" 
            v-model="tab"  
        />
    
        <div class="content">
            <div v-if="tab == 'rulein'">入站规则</div>
            <div v-else-if="tab == 'ruleout'">出站规则</div>
            <div v-else>关联云主机</div> 
        </div>
    </div>
</template>
<script>
import {Tabs, Tab} from 'components/tabs';

export default {
    components: {
        Tabs, Tab
    },
    data() {
        return {
            "tab": "ruleout"
        }
    },
}
</script>
