// components/pagination/demos/counts/index.vue
<template>
    <div>
        <Pagination :total="200" counts="10" />
        <Pagination :total="200" counts="9" />
    </div>
</template>
<script>
import Pagination from 'kpc-vue/components/pagination';

export default {
    components: {
        Pagination
    },
}
</script>
<style lang="stylus" src="./index.styl"></style>

// components/pagination/demos/counts/index.jsx
import React from 'react';
import Pagination from 'kpc/components/pagination';
import './index.styl';

export default class Demo extends React.Component {
    render() {
        return (
            <div>
                <Pagination total={200} counts="10" />
                <Pagination total={200} counts="9" />
            </div>
        )
    }
}
