// components/button/demos/tagName/index.jsx
import React from 'react';
import Button from 'kpc/components/button';

export default class extends React.Component {
    render() {
        return (
            <div>
                <Button tagName="div" type="primary">div元素按钮</Button>
                <Button tagName="div" disabled>disabled div button</Button>
                <Button href="https://www.ksyun.com" target="_blank">超链接按钮</Button>
            </div>
        )
    }
}

// components/button/demos/tagName/index.vue
<template>
    <div>
        <Button tagName="div" type="primary">div元素按钮</Button>
        <Button tagName="div" disabled>disabled div button</Button>
        <Button href="https://www.ksyun.com" target="_blank">超链接按钮</Button>
    </div>
</template>
<script>
import Button from 'kpc/components/button';

export default {
    components: {
        Button
    },
}
</script>
