// components/layout/demos/fix/index.jsx
import React from 'react';
import {Layout, Header, Aside, Body, Footer} from 'kpc/components/layout';
import {Menu, MenuItem} from 'kpc/components/menu';
import Icon from 'kpc/components/icon';
import {Breadcrumb, BreadcrumbItem} from 'kpc/components/breadcrumb';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            "expandedKeys": [],
            "selectedKey": "3-1"
        };
    }

    render() {
        return (
            <Layout className="layout">
                <Header fixed>
                    <div className="logo">LOGO</div>
                    <Menu type="horizontal">
                        <MenuItem key="1">menu 1</MenuItem>
                        <MenuItem key="2" disabled>menu 2</MenuItem>
                        <MenuItem key="3">
                            menu 3
                            <Menu>
                                <MenuItem key="3-1">sub menu 1</MenuItem>
                                <MenuItem key="3-2">sub menu 2</MenuItem>
                                <MenuItem key="3-3" disabled>sub menu 3</MenuItem>
                                <MenuItem key="3-4">
                                    sub menu 4
                                    <Menu>
                                        <MenuItem key="3-4-1">option 1</MenuItem>
                                        <MenuItem key="3-4-2">option 2</MenuItem>
                                    </Menu>
                                </MenuItem>
                            </Menu>
                        </MenuItem>
                        <MenuItem key="4">menu 4</MenuItem>
                    </Menu>
                </Header>
                <Layout>
                    <Aside fixed>
                        <Menu
                            expandedKeys={this.state.expandedKeys}
                            on$change-expandedKeys={(c, expandedKeys) => this.setState({expandedKeys})} 
                            selectedKey={this.state.selectedKey}
                            on$change-selectedKey={(c, selectedKey) => this.setState({selectedKey})}
                            theme="light"
                        >
                            <MenuItem key="1">
                                <Icon className="ion-flag" />menu 1
                                <Menu>
                                    <MenuItem key="1-1">sub menu 1</MenuItem>
                                    <MenuItem key="1-2">sub menu 2</MenuItem>
                                    <MenuItem key="1-3" disabled>sub menu 3</MenuItem>
                                    <MenuItem key="1-4">sub menu 4</MenuItem>
                                </Menu>
                            </MenuItem>
                            <MenuItem key="2" disabled><Icon className="ion-star" />menu 2</MenuItem>
                            <MenuItem key="3">
                                <i className="k-icon ion-heart"></i>menu 3
                                <Menu>
                                    <MenuItem key="3-1">sub menu 1</MenuItem>
                                    <MenuItem key="3-2">sub menu 2</MenuItem>
                                    <MenuItem key="3-3" disabled>sub menu 3</MenuItem>
                                    <MenuItem key="3-4">sub menu 4</MenuItem>
                                </Menu>
                            </MenuItem>
                            <MenuItem key="4"><Icon className="ion-gear-b" />menu 4</MenuItem>
                        </Menu>
                    </Aside>
                    <Body>
                        <Breadcrumb>
                            <BreadcrumbItem>Home</BreadcrumbItem>
                            <BreadcrumbItem>Detail</BreadcrumbItem>
                        </Breadcrumb>
                        <div v-for={Array.apply(null, {length: 100})}>content</div>
                    </Body>
                </Layout>
            </Layout>
        )
    }
}

// components/layout/demos/fix/index.vue
<template>
    <Layout class="layout">
        <Header fixed>
            <div class="logo">LOGO</div>
            <Menu type="horizontal">
                <MenuItem key="1">menu 1</MenuItem>
                <MenuItem key="2" disabled>menu 2</MenuItem>
                <MenuItem key="3">
                    menu 3
                    <Menu>
                        <MenuItem key="3-1">sub menu 1</MenuItem>
                        <MenuItem key="3-2">sub menu 2</MenuItem>
                        <MenuItem key="3-3" disabled>sub menu 3</MenuItem>
                        <MenuItem key="3-4">
                            sub menu 4
                            <Menu>
                                <MenuItem key="3-4-1">option 1</MenuItem>
                                <MenuItem key="3-4-2">option 2</MenuItem>
                            </Menu>
                        </MenuItem>
                    </Menu>
                </MenuItem>
                <MenuItem key="4">menu 4</MenuItem>
            </Menu>
        </Header>
        <Layout>
            <Aside fixed>
                <Menu
                    :expandedKeys.sync="expandedKeys" 
                    :selectedKey.sync="selectedKey"
                    theme="light"
                >
                    <MenuItem key="1">
                        <Icon class="ion-flag" />menu 1
                        <Menu>
                            <MenuItem key="1-1">sub menu 1</MenuItem>
                            <MenuItem key="1-2">sub menu 2</MenuItem>
                            <MenuItem key="1-3" disabled>sub menu 3</MenuItem>
                            <MenuItem key="1-4">sub menu 4</MenuItem>
                        </Menu>
                    </MenuItem>
                    <MenuItem key="2" disabled><Icon class="ion-star" />menu 2</MenuItem>
                    <MenuItem key="3">
                        <i class="k-icon ion-heart"></i>menu 3
                        <Menu>
                            <MenuItem key="3-1">sub menu 1</MenuItem>
                            <MenuItem key="3-2">sub menu 2</MenuItem>
                            <MenuItem key="3-3" disabled>sub menu 3</MenuItem>
                            <MenuItem key="3-4">sub menu 4</MenuItem>
                        </Menu>
                    </MenuItem>
                    <MenuItem key="4"><Icon class="ion-gear-b" />menu 4</MenuItem>
                </Menu>
            </Aside>
            <Body>
                <Breadcrumb>
                    <BreadcrumbItem>Home</BreadcrumbItem>
                    <BreadcrumbItem>Detail</BreadcrumbItem>
                </Breadcrumb>
                <div v-for="(value, key) in Array.apply(null, {length: 100})">content</div>
            </Body>
        </Layout>
    </Layout>
</template>
<script>
import {Layout, Header, Aside, Body, Footer} from 'kpc/components/layout';
import {Menu, MenuItem} from 'kpc/components/menu';
import Icon from 'kpc/components/icon';
import {Breadcrumb, BreadcrumbItem} from 'kpc/components/breadcrumb';

export default {
    components: {
        Layout, Header, Aside, Body, Footer, Menu, MenuItem, Icon, Breadcrumb, BreadcrumbItem
    },
    data() {
        return {
            "expandedKeys": [],
            "selectedKey": "3-1"
        }
    },
}
</script>
