// components/split/demos/nested/index.vue
<template>
    <div class="wrapper">
        <Split>
            <template slot="first">
                <div class="panel">left</div>
            </template>
            <template slot="last">
                <Split mode="vertical">
                    <template slot="first">
                        <div class="panel">right top</div>
                    </template>
                    <template slot="last">
                        <div class="panel">right bottom</div>
                    </template>
                </Split>
            </template>
        </Split>
    </div>
</template>
<script>
import Split from 'kpc/components/split';

export default {
    components: {
        Split
    },
}
</script>

// components/split/demos/nested/index.jsx
import React from 'react';
import Split from 'kpc/components/split';

export default class extends React.Component {
    render() {
        return (
            <div className="wrapper">
                <Split
                    b-first={<><div className="panel">left</div></>}
                    b-last={<>
                        <Split mode="vertical"
                            b-first={<><div className="panel">right top</div></>}
                            b-last={<><div className="panel">right bottom</div></>}
                        >
                        </Split>
                    </>}
                >
                </Split>
            </div>
        )
    }
}
