// components/table/demos/resizable/index.jsx
import React from 'react';
import Table from 'kpc/components/table';
import {Form, FormItem} from 'kpc/components/form';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            "data": [
                {
                    "a": "A",
                    "b": "B",
                    "c": "C"
                },
                {
                    "a": "A",
                    "b": "B",
                    "c": "C"
                }
            ]
        };
    }

    render() {
        const {data} = this.state;
    
        return (
            <div className='no-data-template'>
                <Table 
                    scheme={{
                        a: {
                            title: '通过minColWidth控制最小宽度100px',
                            width: '50%',
                        },
                        b: {
                            title: '单独设置最小宽度300px',
                            minWidth: 300,
                            width: '10%'
                        },
                        c: {
                            title: '标题',
                            width: '40%',
                        }
                    }} 
                    data={data}
                    resizable
                    minColWidth={100}
                    type="grid"
                />
                <Form style={{"marginTop":"20px"}}>
                    <FormItem style={{"width":"100%"}}
                        b-label={<><div style={{"width":"140px"}}>table in table-cell</div></>}
                    >
                        <Table 
                            fixHeader
                            scheme={{
                                a: {
                                    title: '通过minColWidth控制最小宽度100px',
                                    width: '50%',
                                },
                                b: {
                                    title: '单独设置最小宽度300px',
                                    minWidth: 300,
                                    width: '10%'
                                },
                                c: {
                                    title: '标题',
                                    width: '40%',
                                }
                            }} 
                            data={data}
                            resizable
                            minColWidth={100}
                        />
                    </FormItem>
                </Form>
            </div>
        )
    }
}

// components/table/demos/resizable/index.vue
<template>
    <div class='no-data-template'>
        <Table 
            :scheme="{
                a: {
                    title: '通过minColWidth控制最小宽度100px',
                    width: '50%',
                },
                b: {
                    title: '单独设置最小宽度300px',
                    minWidth: 300,
                    width: '10%'
                },
                c: {
                    title: '标题',
                    width: '40%',
                }
            }" 
            :data="data"
            resizable
            :minColWidth="100"
            type="grid"
        />
        <Form style="margin-top: 20px;">
            <FormItem style="width: 100%">
                <template slot="label"><div style="width: 140px">table in table-cell</div></template>
                <Table 
                    fixHeader
                    :scheme="{
                        a: {
                            title: '通过minColWidth控制最小宽度100px',
                            width: '50%',
                        },
                        b: {
                            title: '单独设置最小宽度300px',
                            minWidth: 300,
                            width: '10%'
                        },
                        c: {
                            title: '标题',
                            width: '40%',
                        }
                    }" 
                    :data="data"
                    resizable
                    :minColWidth="100"
                />
            </FormItem>
        </Form>
    </div>
</template>
<script>
import Table from 'kpc/components/table';
import {Form, FormItem} from 'kpc/components/form';

export default {
    components: {
        Table, Form, FormItem
    },
    data() {
        return {
            "data": [
                {
                    "a": "A",
                    "b": "B",
                    "c": "C"
                },
                {
                    "a": "A",
                    "b": "B",
                    "c": "C"
                }
            ]
        }
    },
}
</script>
