// components/datepicker/demos/multiple/index.vue
<template>
    <div>
        <Datepicker multiple v-model="date" clearable />
        You selected: {{ stringify(date) }}
        <br /><br />
        <Datepicker multiple v-model="datetime" type="datetime" />
        You selected: {{ stringify(datetime) }}
    </div>
</template>
<script>
import Datepicker from 'kpc-vue/components/datepicker';

export default {
    components: {
        Datepicker
    },
    data() {
        return {
            "date": null,
            "datetime": null
        }
    },
    methods: {
        stringify(data) { return JSON.stringify(data); },
    },
}
</script>

// components/datepicker/demos/multiple/index.jsx
import React from 'react';
import Datepicker from 'kpc/components/datepicker';

export default class Demo extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }

    render() {
        return (
            <div>
                <Datepicker multiple value={this.state.date} on$change-value={(c, date) => this.setState({date})} clearable />
                You selected: {JSON.stringify(this.state.date)}
                <br /><br />
                <Datepicker multiple value={this.state.datetime} on$change-value={(c, datetime) => this.setState({datetime})} type="datetime" />
                You selected: {JSON.stringify(this.state.datetime)}
            </div>
        )
    }
}
