// components/split/demos/vertical/index.jsx
import React from 'react';
import Split from 'kpc/components/split';

export default class extends React.Component {
    render() {
        return (
            <Split mode="vertical" lastSize="80px"
                b-first={<><div className="panel">top</div></>}
                b-last={<><div className="panel">bottom</div></>}
            >
            </Split>
        )
    }
}

// components/split/demos/vertical/index.vue
<template>
    <Split mode="vertical" lastSize="80px">
        <template slot="first"><div class="panel">top</div></template>
        <template slot="last"><div class="panel">bottom</div></template>
    </Split>
</template>
<script>
import Split from 'kpc/components/split';

export default {
    components: {
        Split
    },
}
</script>
