// components/dialog/demos/hide/index.jsx
import React from 'react';
import Button from 'kpc-react/components/button';
import Dialog from 'kpc-react/components/dialog';
import Input from 'kpc-react/components/input';

export default class Demo extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
        this.onClick = this.onClick.bind(this);
    }

    onClick() {
        this.setState({show: true});
    }
    
    render() {
        return (
            <div>
                <Button onClick={this.onClick} type="primary">Show Dialog</Button>
                <Dialog value={this.state.show} on$change-value={(c, show) => this.setState({show})} title="Dialog Title" ref={i => this.__demo = i} mode="hide">
                    <Input />
                </Dialog>
            </div>
        )
    }
}

// components/dialog/demos/hide/index.vue
<template>
    <div>
        <Button @click="onClick" type="primary">Show Dialog</Button>
        <Dialog v-model="show" title="Dialog Title" ref="__demo" mode="hide">
            <Input />
        </Dialog>
    </div>
</template>
<script>
import Button from 'kpc/components/button';
import Dialog from 'kpc/components/dialog';
import Input from 'kpc/components/input';

export default {
    components: {
        Button, Dialog, Input
    },
    data() {
        return {
            "show": null
        }
    },
    methods: {
        onClick() {
            this.show = true;
        },
    },
}
</script>
