// components/tooltip/demos/position/index.vue
<template>
    <ButtonGroup>
        <Tooltip v-for="(value, key) in ['left', 'right', 'top', 'bottom']"
            :content="value"
            :position="value"
        >
            <Button>{{ value }}</Button>
        </Tooltip>
    </ButtonGroup>
</template>
<script>
import Tooltip from 'kpc-vue/components/tooltip';
import {ButtonGroup, Button} from 'kpc-vue/components/button';

export default {
    components: {
        Tooltip, ButtonGroup, Button
    },
}
</script>

// components/tooltip/demos/position/index.jsx
import React from 'react';
import Tooltip from 'kpc/components/tooltip';
import {ButtonGroup, Button} from 'kpc/components/button';

export default class extends React.Component {
    render() {
        return (
            <ButtonGroup>
                {['left', 'right', 'top', 'bottom'].map((value, key) => {
                    return (
                        <Tooltip
                            content={value}
                            position={value}
                        >
                            <Button>{value}</Button>
                        </Tooltip>
                    )
                })}
            </ButtonGroup>
        )
    }
}
