// components/badge/demos/alone/index.vue
<template>
    <div>
        <Badge />
        <Badge text="new" />
        <Badge :text="19" />
        <Badge :text="100" :max="99" />
    </div>
</template>
<script>
import Badge from 'kpc/components/badge';
import Button from 'kpc/components/button';

export default {
    components: {
        Badge, Button
    },
}
</script>

// components/badge/demos/alone/index.jsx
import React from 'react';
import Badge from 'kpc/components/badge';
import Button from 'kpc/components/button';

export default class extends React.Component {
    render() {
        return (
            <div>
                <Badge />
                <Badge text="new" />
                <Badge text={19} />
                <Badge text={100} max={99} />
            </div>
        )
    }
}
