// components/button/demos/ghost/index.vue
<template>
    <div class="wrapper">
        <Button ghost>default</Button>
        <Button type="primary" ghost>primay</Button>
        <Button type="warning" ghost>warning</Button>
        <Button type="danger" ghost>danger</Button>
        <Button type="success" ghost>success</Button>
        <Button type="none" ghost>none</Button>
        <Button type="primary" ghost disabled>primay</Button>
    </div>
</template>
<script>
import Button from 'kpc/components/button';

export default {
    components: {
        Button
    },
}
</script>

// components/button/demos/ghost/index.jsx
import React from 'react';
import Button from 'kpc/components/button';

export default class extends React.Component {
    render() {
        return (
            <div className="wrapper">
                <Button ghost>default</Button>
                <Button type="primary" ghost>primay</Button>
                <Button type="warning" ghost>warning</Button>
                <Button type="danger" ghost>danger</Button>
                <Button type="success" ghost>success</Button>
                <Button type="none" ghost>none</Button>
                <Button type="primary" ghost disabled>primay</Button>
            </div>
        )
    }
}
