// components/switch/demos/size/index.vue
<template>
    <div>
        large: <KSwitch size="large" />
        default: <KSwitch />
        small: <KSwitch size='small' />
        mini: <KSwitch size='mini' />
    </div>
</template>
<script>
import {Switch as KSwitch} from 'kpc/components/switch';

export default {
    components: {
        KSwitch
    },
}
</script>

// components/switch/demos/size/index.jsx
import React from 'react';
import {Switch} from 'kpc/components/switch';

export default class extends React.Component {
    render() {
        return (
            <div>
                large: <Switch size="large" />
                default: <Switch />
                small: <Switch size='small' />
                mini: <Switch size='mini' />
            </div>
        )
    }
}
