// components/button/demos/disabled/index.jsx
import React from 'react';
import Button from 'kpc/components/button';

export default class extends React.Component {
    render() {
        return (
            <div>
                <Button disabled>disabled</Button>
                <Button disabled type="none">disabled text</Button>
                <Button disabled icon circle><i className="k-icon ion-ios-search"></i></Button>
            </div>
        )
    }
}

// components/button/demos/disabled/index.vue
<template>
    <div>
        <Button disabled>disabled</Button>
        <Button disabled type="none">disabled text</Button>
        <Button disabled icon circle><i class="k-icon ion-ios-search"></i></Button>
    </div>
</template>
<script>
import Button from 'kpc/components/button';

export default {
    components: {
        Button
    },
}
</script>
