// components/dialog/demos/terminate/index.vue
<template>
    <div>
        <Button @click="onClick" type="primary">Show Dialog</Button>
        <Dialog v-model="show" title="Dialog Title" ref="__demo"
            :terminate="_terminate"
            :cancel="_terminate"
        >
            Dialog Body 
        </Dialog>
    </div>
</template>
<script>
import Button from 'kpc/components/button';
import Dialog from 'kpc/components/dialog';


export default {
    components: {
        Button, Dialog
    },
    data() {
        return {
            "show": null
        }
    },
    methods: {
        onClick() {
            this.show = true;
        },
        _terminate() {
            Dialog.confirm({
                content: 'Are you sure you want to close the dialog?'
            }).then(() => {
                this.show = false;
            }, () => {});
        },
    },
}
</script>

// components/dialog/demos/terminate/index.jsx
import React from 'react';
import Button from 'kpc/components/button';
import Dialog from 'kpc/components/dialog';

export default class Demo extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
        this.onClick = this.onClick.bind(this);
        this._terminate = this._terminate.bind(this);
    }

    onClick() {
        this.setState({show: true});
    }
    
    _terminate() {
        Dialog.confirm({
            content: 'Are you sure you want to close the dialog?'
        }).then(() => {
            this.setState({show: false});
        }, () => {});
    }
    
    render() {
        return (
            <div>
                <Button onClick={this.onClick} type="primary">Show Dialog</Button>
                <Dialog value={this.state.show} on$change-value={(c, show) => this.setState({show})} title="Dialog Title" ref={i => this.__demo = i}
                    terminate={this._terminate}
                    cancel={this._terminate}
                >
                    Dialog Body 
                </Dialog>
            </div>
        )
    }
}
