// components/message/demos/duration/index.jsx
import React from 'react';
import {ButtonGroup, Button} from 'kpc/components/button';


export default class extends React.Component {
    constructor(props) {
        super(props);
        this.showMessage1 = this.showMessage1.bind(this);
        this.showMessage2 = this.showMessage2.bind(this);
    }

    showMessage1() {
        Message.info('close after 10s', 10000);
    }
    
    showMessage2() {
        Message.info('stick message', 0);
    }
    
    render() {
        return (
            <ButtonGroup>
                <Button onClick={this.showMessage1}>close after 10s</Button>
                <Button onClick={this.showMessage2}>stick message</Button>
            </ButtonGroup>
        )
    }
}

// components/message/demos/duration/index.vue
<template>
    <ButtonGroup>
        <Button @click="showMessage1">close after 10s</Button>
        <Button @click="showMessage2">stick message</Button>
    </ButtonGroup>
</template>
<script>
import {ButtonGroup, Button} from 'kpc/components/button';

import Message from 'kpc/components/message';

export default {
    components: {
        ButtonGroup, Button
    },
    methods: {
        showMessage1() {
            Message.info('close after 10s', 10000);
        },
        showMessage2() {
            Message.info('stick message', 0);
        },
    },
}
</script>
