// components/split/demos/range/index.jsx
import React from 'react';
import Split from 'kpc/components/split';

export default class extends React.Component {
    render() {
        return (
            <Split min="40" max="50%+10" firstSize="80px"
                b-first={<><div className="panel">left</div></>}
                b-last={<><div className="panel">right</div></>}
            >
            </Split>
        )
    }
}

// components/split/demos/range/index.vue
<template>
    <Split min="40" max="50%+10" firstSize="80px">
        <template slot="first"><div class="panel">left</div></template>
        <template slot="last"><div class="panel">right</div></template>
    </Split>
</template>
<script>
import Split from 'kpc/components/split';

export default {
    components: {
        Split
    },
}
</script>
