// components/table/demos/export/index.vue
<template>
    <div>
        <Button type="primary" @click="_export">导出表格</Button>
        <Button type="primary" @click="_exportData">导出自定义数据</Button>
        <Table :data="data" ref="table">
            <TableColumn title="定义该列单元格内容" key="a">
                <template slot="template" slot-scope="data">
                    <a>{{ data.a }}</a>
                </template>
            </TableColumn>
            <TableColumn title="普通文本" key="b" />
            <TableColumn title="自定义导出文本" key="c">
                <template slot="template" slot-scope="data">
                    <div :data-text="'自定义导出文本:' + data.c">
                        {{ data.c }}
                    </div>
                </template>
            </TableColumn>
            <TableColumn title="操作" key="op" ignore align="right">
                <template slot="template" slot-scope="data">
                    <a>删除</a> 
                </template>
            </TableColumn>
        </Table>
    </div>
</template>
<script>
import {Table, TableColumn} from 'kpc/components/table';
import {Button} from 'kpc/components/button';

export default {
    components: {
        Table, TableColumn, Button
    },
    data() {
        return {
            "data": [
                {
                    "a": "第一行",
                    "b": "哈哈1",
                    "c": "自定义1"
                },
                {
                    "a": "第二行",
                    "b": "哈哈2",
                    "c": "自定义2"
                }
            ]
        }
    },
    methods: {
        _export() {
            this.$refs.table.exportTable();
        },
        _exportData() {
            this.$refs.table.exportTable([
                {a: '第一行', b: '哈哈1', c: '自定义1'}, 
                {a: '第二行', b: '哈哈2', c: '自定义2'},
                {a: '第三行', b: '哈哈3', c: '自定义3'}
            ]);
        },
    },
}
</script>

// components/table/demos/export/index.jsx
import React from 'react';
import {Table, TableColumn} from 'kpc/components/table';
import {Button} from 'kpc/components/button';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            "data": [
                {
                    "a": "第一行",
                    "b": "哈哈1",
                    "c": "自定义1"
                },
                {
                    "a": "第二行",
                    "b": "哈哈2",
                    "c": "自定义2"
                }
            ]
        };
        this._export = this._export.bind(this);
        this._exportData = this._exportData.bind(this);
    }

    _export() {
        this.table.exportTable();
    }
    
    _exportData() {
        this.table.exportTable([
            {a: '第一行', b: '哈哈1', c: '自定义1'}, 
            {a: '第二行', b: '哈哈2', c: '自定义2'},
            {a: '第三行', b: '哈哈3', c: '自定义3'}
        ]);
    }
    
    render() {
        return (
            <div>
                <Button type="primary" onClick={this._export}>导出表格</Button>
                <Button type="primary" onClick={this._exportData}>导出自定义数据</Button>
                <Table data={this.state.data} ref={i => this.table = i}>
                    <TableColumn title="定义该列单元格内容" key="a"
                        b-template={(data) => {
                            return <>
                                <a>{data.a}</a>
                            </>
                        }}
                    >
                    </TableColumn>
                    <TableColumn title="普通文本" key="b" />
                    <TableColumn title="自定义导出文本" key="c"
                        b-template={(data) => {
                            return <>
                                <div data-text={'自定义导出文本:' + data.c}>
                                    {data.c}
                                </div>
                            </>
                        }}
                    >
                    </TableColumn>
                    <TableColumn title="操作" key="op" ignore align="right"
                        b-template={(data) => {
                            return <>
                                <a>删除</a> 
                            </>
                        }}
                    >
                    </TableColumn>
                </Table>
            </div>
        )
    }
}
