// components/carousel/demos/multiple/index.jsx
import React from 'react';
import {Carousel, CarouselItem} from 'kpc/components/carousel';
import './index.styl';

export default class Demo extends React.Component {
    render() {
        return (
            <Carousel clonedAmount={2}>
                <CarouselItem className="one">1</CarouselItem>
                <CarouselItem className="two">2</CarouselItem>
                <CarouselItem className="three">3</CarouselItem>
                <CarouselItem className="four">4</CarouselItem>
            </Carousel>
        )
    }
}

// components/carousel/demos/multiple/index.vue
<template>
    <Carousel :clonedAmount="2">
        <CarouselItem class="one">1</CarouselItem>
        <CarouselItem class="two">2</CarouselItem>
        <CarouselItem class="three">3</CarouselItem>
        <CarouselItem class="four">4</CarouselItem>
    </Carousel>
</template>
<script>
import {Carousel, CarouselItem} from 'kpc-vue/components/carousel';

export default {
    components: {
        Carousel, CarouselItem
    },
}
</script>
<style lang="stylus" src="./index.styl"></style>
