// components/radio/demos/group/index.vue
<template>
    <div>
        <Radio name="language" trueValue="Javascript" v-model="language">Javascript</Radio>
        <Radio name="language" trueValue="C++" v-model="language">C++</Radio>
        <Radio name="language" trueValue="PHP" v-model="language">PHP</Radio>
        Your selected: {{ language }}
    </div>
</template>
<script>
import Radio from 'kpc/components/radio';

export default {
    components: {
        Radio
    },
    data() {
        return {
            "language": null
        }
    },
}
</script>

// components/radio/demos/group/index.jsx
import React from 'react';
import Radio from 'kpc/components/radio';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }

    render() {
        return (
            <div>
                <Radio name="language" trueValue="Javascript" value={this.state.language} on$change-value={(c, language) => this.setState({language})}>Javascript</Radio>
                <Radio name="language" trueValue="C++" value={this.state.language} on$change-value={(c, language) => this.setState({language})}>C++</Radio>
                <Radio name="language" trueValue="PHP" value={this.state.language} on$change-value={(c, language) => this.setState({language})}>PHP</Radio>
                Your selected: {this.state.language}
            </div>
        )
    }
}
