// components/timepicker/demos/step/index.vue
<template>
    <div>
        <Timepicker class="time" v-model="time" step="00:30:00"/>
        You selected: {{ stringify(time) }}
        <br /><br />
        <Timepicker v-model="timeArray" multiple clearable
            step="00:30:00" 
            min="09:00:00"
            max="18:00:00"
        />
        You selected: {{ stringify(timeArray) }}
    </div>
</template>
<script>
import Timepicker from 'kpc-vue/components/timepicker';

export default {
    components: {
        Timepicker
    },
    data() {
        return {
            "time": null,
            "timeArray": null
        }
    },
    methods: {
        stringify(data) { return JSON.stringify(data); },
    },
}
</script>

// components/timepicker/demos/step/index.jsx
import React from 'react';
import Timepicker from 'kpc/components/timepicker';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }

    render() {
        return (
            <div>
                <Timepicker className="time" value={this.state.time} on$change-value={(c, time) => this.setState({time})} step="00:30:00"/>
                You selected: {JSON.stringify(this.state.time)}
                <br /><br />
                <Timepicker value={this.state.timeArray} on$change-value={(c, timeArray) => this.setState({timeArray})} multiple clearable
                    step="00:30:00" 
                    min="09:00:00"
                    max="18:00"
                />
                You selected: {JSON.stringify(this.state.timeArray)}
            </div>
        )
    }
}
