// components/upload/demos/gallery/index.vue
<template>
    <Upload multiple
        action="//jsonplaceholder.typicode.com/posts/"
        type="gallery"
        :limit="3"
        accept=".jpg, .png"
        @error="_onError"
    />
</template>
<script>
import Upload from 'kpc-vue/components/upload';

import Dialog from 'kpc-vue/components/dialog';
import Message from 'kpc-vue/components/message';

export default {
    components: {
        Upload
    },
    methods: {
        _onError(err) {
            Message.error(err.message);
        },
    },
}
</script>

// components/upload/demos/gallery/index.jsx
import React from 'react';
import Upload from 'kpc/components/upload';
import Dialog from 'kpc/components/dialog';
import Message from 'kpc/components/message';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this._onError = this._onError.bind(this);
    }

    _onError(err) {
        Message.error(err.message);
    }
    
    render() {
        return (
            <Upload multiple
                action="//jsonplaceholder.typicode.com/posts/"
                type="gallery"
                limit={3}
                accept=".jpg, .png"
                onError={this._onError}
            />
        )
    }
}
