// components/tag/demos/closable/index.jsx
import React from 'react';
import Tag from 'kpc/components/tag';

export default class extends React.Component {
    render() {
        return (
            <div>
                {['default', 'primary', 'success', 'warning', 'danger'].map((value, key) => {
                    return (
                        <Tag
                            key={value}
                            type={value}
                            closable
                        >{value}</Tag>
                    )
                })}
                <Tag disabled closable>disabled</Tag>
            </div>
        )
    }
}

// components/tag/demos/closable/index.vue
<template>
    <div>
        <Tag v-for="(value, key) in ['default', 'primary', 'success', 'warning', 'danger']"
            :key="value"
            :type="value"
            closable
        >{{ value }}</Tag>
        <Tag disabled closable>disabled</Tag>
    </div>
</template>
<script>
import Tag from 'kpc/components/tag';

export default {
    components: {
        Tag
    },
}
</script>
