// components/datepicker/demos/range/index.vue
<template>
    <div>
        <Datepicker range v-model="date" />
        You selected: {{ stringify(date) }}
        <br /><br />
        <Datepicker range type="datetime" v-model="time" />
        You selected: {{ stringify(time) }}
    </div>
</template>
<script>
import Datepicker from 'kpc/components/datepicker';

export default {
    components: {
        Datepicker
    },
    data() {
        return {
            "date": null,
            "time": null
        }
    },
    methods: {
        stringify(data) { return JSON.stringify(data); },
    },
}
</script>

// components/datepicker/demos/range/index.jsx
import React from 'react';
import Datepicker from 'kpc/components/datepicker';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }

    render() {
        return (
            <div>
                <Datepicker range value={this.state.date} on$change-value={(c, date) => this.setState({date})} />
                You selected: {JSON.stringify(this.state.date)}
                <br /><br />
                <Datepicker range type="datetime" value={this.state.time} on$change-value={(c, time) => this.setState({time})} />
                You selected: {JSON.stringify(this.state.time)}
            </div>
        )
    }
}
