// components/switch/demos/value/index.jsx
import React from 'react';
import {Switch} from 'kpc/components/switch';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }

    render() {
        return (
            <div>
                <div style={{"marginBottom":"20px"}}>
                    <Switch value={this.state.value1} on$change-value={(c, value1) => this.setState({value1})} />
                    {JSON.stringify(this.state.value1)}
                </div>
                <div>
                    <Switch value={this.state.value2} on$change-value={(c, value2) => this.setState({value2})} trueValue={1} falseValue="1" />
                    {JSON.stringify(this.state.value2)}
                </div>
            </div>
        )
    }
}

// components/switch/demos/value/index.vue
<template>
    <div>
        <div style="margin-bottom: 20px">
            <KSwitch v-model="value1" />
            {{ stringify(value1) }}
        </div>
        <div>
            <KSwitch v-model="value2" :trueValue="1" falseValue="1" />
            {{ stringify(value2) }}
        </div>
    </div>
</template>
<script>
import {Switch as KSwitch} from 'kpc-vue/components/switch';

export default {
    components: {
        KSwitch
    },
    data() {
        return {
            "value1": null,
            "value2": null
        }
    },
    methods: {
        stringify(data) { return JSON.stringify(data); },
    },
}
</script>
