// components/tooltip/demos/content/index.jsx
import React from 'react';
import Tooltip from 'kpc/components/tooltip';
import {Slider} from 'kpc/components/slider';
import {Button} from 'kpc/components/button';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
    }

    render() {
        return (
            <div>
                <Tooltip trigger="click"
                    b-content={<>
                        <Slider value={this.state.volume}
                            on$change-value={(c, volume) => this.setState({volume})} 
                            style={{"width":"200px"}}
                            isShowInput={false} 
                            isShowEnd={false}
                        />
                    </>}
                >
                    <Button>Adjust Volume</Button>
                </Tooltip>
            </div>
        )
    }
}

// components/tooltip/demos/content/index.vue
<template>
    <div>
        <Tooltip trigger="click">
            <Button>Adjust Volume</Button>
            <template slot="content">
                <Slider v-model="volume" 
                    style="width: 200px;"
                    :isShowInput="false" 
                    :isShowEnd="false"
                />
            </template>
        </Tooltip>
    </div>
</template>
<script>
import Tooltip from 'kpc/components/tooltip';
import {Slider} from 'kpc/components/slider';
import {Button} from 'kpc/components/button';

export default {
    components: {
        Tooltip, Slider, Button
    },
    data() {
        return {
            "volume": null
        }
    },
}
</script>
