// components/message/demos/config/index.vue
<template>
    <ButtonGroup>
        <Button v-for="(value, key) in ['info', 'error', 'warning', 'success']"
            @click="showMessage(value)"
        >{{ value }}</Button>
    </ButtonGroup>
</template>
<script>
import {ButtonGroup, Button} from 'kpc/components/button';

import Message from 'kpc/components/message';

export default {
    components: {
        ButtonGroup, Button
    },
    methods: {
        showMessage(type) {
            Message[type]({
                content: type,
                duration: 3000,
                type: type,
                closable: false,
                hideIcon: true,
            });
        },
    },
}
</script>

// components/message/demos/config/index.jsx
import React from 'react';
import {ButtonGroup, Button} from 'kpc/components/button';

import Message from 'kpc/components/message';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.showMessage = this.showMessage.bind(this);
    }

    showMessage(type) {
        Message[type]({
            content: type,
            duration: 3000,
            type: type,
            closable: false,
            hideIcon: true,
        });
    }
    
    render() {
        return (
            <ButtonGroup>
                {['info', 'error', 'warning', 'success'].map((value, key) => {
                    return (
                        <Button
                            onClick={this.showMessage.bind(this, value)}
                        >{value}</Button>
                    )
                })}
            </ButtonGroup>
        )
    }
}
