// components/spinner/demos/size/index.jsx
import React from 'react';
import Spinner from 'kpc/components/spinner';
import './index.styl';

export default class Demo extends React.Component {
    render() {
        return (
            <div>
                <Spinner size="large" />
                <Spinner />
                <Spinner size="small" />
                <Spinner size="mini" />
            </div>
        )
    }
}

// components/spinner/demos/size/index.vue
<template>
    <div>
        <Spinner size="large" />
        <Spinner />
        <Spinner size="small" />
        <Spinner size="mini" />
    </div>
</template>
<script>
import Spinner from 'kpc-vue/components/spinner';

export default {
    components: {
        Spinner
    },
}
</script>
<style lang="stylus" src="./index.styl"></style>
