// components/breadcrumb/demos/separator/index.vue
<template>
    <Breadcrumb separator="<b class='separator'>=></b>">
        <BreadcrumbItem to="/">
            <i class="ion-home" /> item 1
        </BreadcrumbItem>
        <BreadcrumbItem to="/components/breadcrumb/">
            <i class="ion-earth" /> item 2
        </BreadcrumbItem>
        <BreadcrumbItem>
            <i class="ion-planet" /> item 3
        </BreadcrumbItem>
    </Breadcrumb>
</template>
<script>
import {Breadcrumb, BreadcrumbItem} from 'kpc/components/breadcrumb';

export default {
    components: {
        Breadcrumb, BreadcrumbItem
    },
}
</script>

// components/breadcrumb/demos/separator/index.jsx
import React from 'react';
import {Breadcrumb, BreadcrumbItem} from 'kpc/components/breadcrumb';

export default class extends React.Component {
    render() {
        return (
            <Breadcrumb
                b-separator={<><b className="separator">=></b></>}
            >
                <BreadcrumbItem to="/">
                    <i className="ion-home" /> item 1
                </BreadcrumbItem>
                <BreadcrumbItem to="/components/breadcrumb/">
                    <i className="ion-earth" /> item 2
                </BreadcrumbItem>
                <BreadcrumbItem>
                    <i className="ion-planet" /> item 3
                </BreadcrumbItem>
            </Breadcrumb>
        )
    }
}
