// components/carousel/demos/autoplay/index.jsx
import React from 'react';
import {Carousel, CarouselItem} from 'kpc/components/carousel';
import './index.styl';

export default class Demo extends React.Component {
    render() {
        return (
            <Carousel autoplay>
                <CarouselItem>1</CarouselItem>
                <CarouselItem>2</CarouselItem>
                <CarouselItem>3</CarouselItem>
                <CarouselItem>4</CarouselItem>
            </Carousel>
        )
    }
}

// components/carousel/demos/autoplay/index.vue
<template>
    <Carousel autoplay>
        <CarouselItem>1</CarouselItem>
        <CarouselItem>2</CarouselItem>
        <CarouselItem>3</CarouselItem>
        <CarouselItem>4</CarouselItem>
    </Carousel>
</template>
<script>
import {Carousel, CarouselItem} from 'kpc-vue/components/carousel';

export default {
    components: {
        Carousel, CarouselItem
    },
}
</script>
<style lang="stylus" src="./index.styl"></style>
