// components/dropdown/demos/contextmenu/index.jsx
import React from 'react';
import {DropdownMenu, DropdownItem} from 'kpc/components/dropdown';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            "show": false,
            "event": null
        };
        this._showMenu = this._showMenu.bind(this);
    }

    _showMenu(event) {
        // https://reactjs.org/docs/events.html#event-pooling
        event.persist();
        event.preventDefault();
        this.setState({
            show: true,
            event: event,
        });
    }
    
    render() {
        return (
            <div>
                <div className="contextmenu-area" onContextMenu={this._showMenu}>
                    right click this area to show context menu
                </div>
                <DropdownMenu value={this.state.show}
                    on$change-value={(c, show) => this.setState({show})} 
                    of={this.state.event}
                    position={{my: 'left+1 top', at: 'right bottom'}}
                >
                    <DropdownItem>Option 1</DropdownItem>
                    <DropdownItem>Option 2</DropdownItem>
                    <DropdownItem>Option 3</DropdownItem>
                </DropdownMenu>
            </div>
        )
    }
}

// components/dropdown/demos/contextmenu/index.vue
<template>
    <div>
        <div class="contextmenu-area" @contextmenu="_showMenu">
            right click this area to show context menu
        </div>
        <DropdownMenu v-model="show" 
            :of="event"
            :position="{my: 'left+1 top', at: 'right bottom'}"
        >
            <DropdownItem>Option 1</DropdownItem>
            <DropdownItem>Option 2</DropdownItem>
            <DropdownItem>Option 3</DropdownItem>
        </DropdownMenu>
    </div>
</template>
<script>
import {DropdownMenu, DropdownItem} from 'kpc/components/dropdown';

export default {
    components: {
        DropdownMenu, DropdownItem
    },
    data() {
        return {
            "event": null,
            "show": false
        }
    },
    methods: {
        _showMenu(event) {
            event.preventDefault();
            this.show = true;
            this.event = event;
        },
    },
}
</script>
