// components/tooltip/demos/always/index.jsx
import React from 'react';
import Tooltip from 'kpc/components/tooltip';

export default class Demo extends React.Component {
    render() {
        return (
            <div>
                <Tooltip content="hello" always value={true}>
                    always show this tootip 
                </Tooltip>
                <br /><br />
                <Tooltip content="" always value={true}>
                    don't show if content is empty
                </Tooltip>
            </div>
        )
    }
}

// components/tooltip/demos/always/index.vue
<template>
    <div>
        <Tooltip content="hello" always :value="true">
            always show this tootip 
        </Tooltip>
        <br /><br />
        <Tooltip content="" always :value="true">
            don't show if content is empty
        </Tooltip>
    </div>
</template>
<script>
import Tooltip from 'kpc-vue/components/tooltip';

export default {
    components: {
        Tooltip
    },
}
</script>
