// components/input/demos/blocks/index.vue
<template>
    <div>
        <Input placeholder="please enter">
            <template slot="prepend">http://</template>
            <template slot="append">.com</template>
        </Input>
        <Input placeholder="please enter">
            <template slot="append"><Button icon type="none"><i class="ion-ios-search"></i></Button></template>
        </Input>
        <Input placeholder="please enter">
            <template slot="append"><Button icon type="primary"><i class="ion-ios-search"></i></Button></template>
        </Input>
        <Input placeholder="please enter">
            <template slot="append"><Button type="primary">搜索</Button></template>
        </Input>
        <Input placeholder="please enter">
            <template slot="prefix"><i class="ion-earth"></i></template>
            <template slot="suffix"><i class="ion-ios-search"></i></template>
        </Input>
        <Input placeholder="please enter">
            <template slot="prepend">http://</template>
            <template slot="append">.com</template>
            <template slot="prefix"><i class="ion-earth"></i></template>
            <template slot="suffix"><i class="ion-ios-search"></i></template>
        </Input>
    </div>
</template>
<script>
import Input from 'kpc/components/input';
import Button from 'kpc/components/button';

export default {
    components: {
        Input, Button
    },
}
</script>

// components/input/demos/blocks/index.jsx
import React from 'react';
import Input from 'kpc/components/input';
import Button from 'kpc/components/button';

export default class extends React.Component {
    render() {
        return (
            <div>
                <Input placeholder="please enter"
                    b-prepend={<>http://</>}
                    b-append={<>.com</>}
                >
                </Input>
                <Input placeholder="please enter"
                    b-append={<><Button icon type="none"><i className="ion-ios-search"></i></Button></>}
                >
                </Input>
                <Input placeholder="please enter"
                    b-append={<><Button icon type="primary"><i className="ion-ios-search"></i></Button></>}
                >
                </Input>
                <Input placeholder="please enter"
                    b-append={<><Button type="primary">搜索</Button></>}
                >
                </Input>
                <Input placeholder="please enter"
                    b-prefix={<><i className="ion-earth"></i></>}
                    b-suffix={<><i className="ion-ios-search"></i></>}
                >
                </Input>
                <Input placeholder="please enter"
                    b-prepend={<>http://</>}
                    b-append={<>.com</>}
                    b-prefix={<><i className="ion-earth"></i></>}
                    b-suffix={<><i className="ion-ios-search"></i></>}
                >
                </Input>
            </div>
        )
    }
}
