// components/checkbox/demos/group/index.vue
<template>
    <div>
        <Checkbox name="languages" trueValue="Javascript" v-model="languages">Javascript</Checkbox>
        <Checkbox name="languages" trueValue="C++" v-model="languages">C++</Checkbox>
        <Checkbox name="languages" trueValue="PHP" v-model="languages">PHP</Checkbox>
        Your selected: {{ stringify(languages) }}
    </div>
</template>
<script>
import Checkbox from 'kpc/components/checkbox';

export default {
    components: {
        Checkbox
    },
    data() {
        return {
            "languages": []
        }
    },
    methods: {
        stringify(data) { return JSON.stringify(data); },
    },
}
</script>

// components/checkbox/demos/group/index.jsx
import React from 'react';
import Checkbox from 'kpc/components/checkbox';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            "languages": []
        };
    }

    render() {
        return (
            <div>
                <Checkbox name="languages" trueValue="Javascript" value={this.state.languages} on$change-value={(c, languages) => this.setState({languages})}>Javascript</Checkbox>
                <Checkbox name="languages" trueValue="C++" value={this.state.languages} on$change-value={(c, languages) => this.setState({languages})}>C++</Checkbox>
                <Checkbox name="languages" trueValue="PHP" value={this.state.languages} on$change-value={(c, languages) => this.setState({languages})}>PHP</Checkbox>
                Your selected: {JSON.stringify(this.state.languages)}
            </div>
        )
    }
}
