// components/select/demos/remote/index.vue
<template>
    <Select filterable :filter="() => true" @$change:keywords="search">
        <Option v-for="(value, key) in users" 
            :value="value.login.username"
        >{{ value.name.first }} {{ value.name.last }}</Option>
    </Select>
</template>
<script>
import {Select, Option} from 'kpc-vue/components/select';

export default {
    components: {
        Select, Option
    },
    data() {
        return {
            "users": []
        }
    },
    methods: {
        search(select, keywords) {
            console.log(keywords);
        
            if (!keywords) return;
        
            const fetchId = ++this.lastFetchId
            fetch('https://randomuser.me/api/?results=10')
                .then(response => response.json())
                .then(body => {
                    if (fetchId !== this.lastFetchId) return;
                    this.users = body.results;
                });
        },
    },
    beforeCreate() {
        this.lastFetchId = 0;
    },
}
</script>

// components/select/demos/remote/index.jsx
import React from 'react';
import {Select, Option} from 'kpc/components/select';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {users: []};
        this.search = this.search.bind(this);
        this.lastFetchId = 0;
    }
    
    search(select, keywords) {
        console.log(keywords);
    
        if (!keywords) return;
    
        const fetchId = ++this.lastFetchId
        fetch('https://randomuser.me/api/?results=10')
            .then(response => response.json())
            .then(body => {
                if (fetchId !== this.lastFetchId) return;
                this.setState({users: body.results});
            });
    }
    
    render() {
        return (
            <Select filterable filter={() => true} on$change-keywords={this.search}>
                {this.state.users.map((value, key) => {
                    return (
                        <Option 
                            value={value.login.username}
                        >{value.name.first} {value.name.last}</Option>
                    )
                })}
            </Select>
        )
    }
}
