// components/progress/demos/innerText/index.vue
<template>
    <div>
        <Progress percent="0" :isInnerText="true" :isOuterText="false" />
        <Progress percent="50" :isInnerText="true" :isOuterText="false" />
        <Progress percent="60" status="error" :isInnerText="true" :isOuterText="false" />
        <Progress percent="70" status="success" :isInnerText="true" :isOuterText="false" />
    </div>
</template>
<script>
import Progress from 'kpc/components/progress';

export default {
    components: {
        Progress
    },
}
</script>

// components/progress/demos/innerText/index.jsx
import React from 'react';
import Progress from 'kpc/components/progress';

export default class extends React.Component {
    render() {
        return (
            <div>
                <Progress percent="0" isInnerText={true} isOuterText={false} />
                <Progress percent="50" isInnerText={true} isOuterText={false} />
                <Progress percent="60" status="error" isInnerText={true} isOuterText={false} />
                <Progress percent="70" status="success" isInnerText={true} isOuterText={false} />
            </div>
        )
    }
}
