// components/radio/demos/value/index.jsx
import React from 'react';
import Radio from 'kpc/components/radio';

export default class extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            "checkedValue": {
                "test": 1
            }
        };
    }

    render() {
        return (
            <div>
                <Radio value={this.state.value1} on$change-value={(c, value1) => this.setState({value1})}>默认值：{JSON.stringify(this.state.value1)}</Radio>
                <Radio value={this.state.value2} on$change-value={(c, value2) => this.setState({value2})} trueValue="checked">
                    指定选中时的取值为"checked": {JSON.stringify(this.state.value2)}
                </Radio>
                <Radio value={this.state.value3} on$change-value={(c, value3) => this.setState({value3})} trueValue={this.state.checkedValue}>
                    指定选中时的取值为对象：{JSON.stringify(this.state.value3)}
                </Radio>
            </div>
        )
    }
}

// components/radio/demos/value/index.vue
<template>
    <div>
        <Radio v-model="value1">默认值：{{ stringify(value1) }}</Radio>
        <Radio v-model="value2" trueValue="checked">
            指定选中时的取值为"checked": {{ stringify(value2) }}
        </Radio>
        <Radio v-model="value3" :trueValue="checkedValue">
            指定选中时的取值为对象：{{ stringify(value3) }}
        </Radio>
    </div>
</template>
<script>
import Radio from 'kpc/components/radio';

export default {
    components: {
        Radio
    },
    data() {
        return {
            "checkedValue": {
                "test": 1
            },
            "value1": null,
            "value2": null,
            "value3": null
        }
    },
    methods: {
        stringify(data) { return JSON.stringify(data); },
    },
}
</script>
