// components/slider/demos/disabled/index.jsx
import React from 'react';
import Slider from 'kpc/components/slider';

export default class extends React.Component {
    render() {
        return (
            <div>
                <Slider disabled value={50} />
                <Slider disabled isRange value={[55, 80]} min={50} max={100} />
            </div>
        )
    }
}

// components/badge/demos/disabled/index.vue
<template>
    <div>
        <Badge disabled>Message</Badge>
        <Badge disabled>
            <Button>Message</Button>
        </Badge>
        <Badge :text="19" disabled>
            <Button>Message</Button>
        </Badge>
        <Badge :text="100" :max="99" disabled>
            <Button>Message</Button>
        </Badge>
    </div>
</template>
<script>
import Badge from 'kpc/components/badge';
import Button from 'kpc/components/button';

export default {
    components: {
        Badge, Button
    },
}
</script>
