// components/datepicker/demos/disabledDate/index.jsx
import React from 'react';
import Datepicker from 'kpc/components/datepicker';

export default class extends React.Component {
    render() {
        return (
            <Datepicker disabledDate={(date) => {
                // 禁用掉2018-02-05和2018-03-05
                return ~['2018-02-05', '2018-03-05'].indexOf(date);
            }} />
        )
    }
}

// components/datepicker/demos/disabledDate/index.vue
<template>
    <Datepicker :disabledDate="(date) => {
        // 禁用掉2018-02-05和2018-03-05
        return ~['2018-02-05', '2018-03-05'].indexOf(date);
    }" />
</template>
<script>
import Datepicker from 'kpc/components/datepicker';

export default {
    components: {
        Datepicker
    },
}
</script>
