// components/tip/demos/title/index.jsx
import React from 'react';
import Tip from 'kpc/components/tip';

export default class extends React.Component {
    render() {
        return (
            <div>
                {['default', 'primary', 'success', 'warning', 'danger'].map((value, key) => {
                    return (
                        <Tip
                            b-title={<>{value}</>}
                            key={value}
                            type={value}
                            closable
                        >
                            This is a {value} tip.
                        </Tip>
                    )
                })}
            </div>
        )
    }
}

// components/tip/demos/title/index.vue
<template>
    <div>
        <Tip v-for="(value, key) in ['default', 'primary', 'success', 'warning', 'danger']"
            :key="value"
            :type="value"
            closable
        >
            <template slot="title">{{ value }}</template>
            This is a {{ value }} tip.
        </Tip>
    </div>
</template>
<script>
import Tip from 'kpc/components/tip';

export default {
    components: {
        Tip
    },
}
</script>
